# Generated by Django 5.1.1 on 2024-09-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_product_options_rename_sizs_product_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizs',
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(),
        ),
    ]
